import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo, useState } from 'react';
import { api } from '../api/client';
import { useApi } from '../hooks/useApi';
import { AlertFilterBar } from '../components/AlertFilterBar';
import { ClassificationBadge } from '../components/ClassificationBadge';
import { formatDateTime } from '../lib/format';
import { EMPTY_FILTER, filterAlerts } from '../lib/alertFilter';
export default function AlertsPage() {
    const [showAcked, setShowAcked] = useState(false);
    const fetcher = showAcked ? api.alertsAll : api.alertsActive;
    const alerts = useApi(fetcher, { intervalMs: 5000, deps: [showAcked] });
    const [filter, setFilter] = useState(EMPTY_FILTER);
    const allAlerts = alerts.data ?? [];
    // Pass null for the zone — clicking the building map is a Dashboard-only
    // affordance. The bar will not display the zone chip.
    const visibleAlerts = useMemo(() => filterAlerts(allAlerts, filter, null), [allAlerts, filter]);
    return (_jsxs("div", { className: "max-w-7xl mx-auto px-4 py-6 space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h1", { className: "text-lg font-semibold tracking-wide", children: "Alerts" }), _jsxs("label", { className: "flex items-center gap-2 text-sm font-mono text-gray-400", children: [_jsx("input", { type: "checkbox", checked: showAcked, onChange: (e) => setShowAcked(e.target.checked), className: "accent-critical" }), "Include acknowledged"] })] }), _jsxs("div", { className: "bg-panel border border-border rounded-lg overflow-hidden", children: [_jsx(AlertFilterBar, { alerts: allAlerts, filter: filter, onChange: setFilter, filteredCount: visibleAlerts.length, totalCount: allAlerts.length }), _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "bg-black/40 text-[10px] uppercase tracking-wider text-gray-500 font-mono", children: _jsxs("tr", { children: [_jsx("th", { className: "text-left px-3 py-2", children: "Created" }), _jsx("th", { className: "text-left px-3 py-2", children: "Class." }), _jsx("th", { className: "text-left px-3 py-2", children: "Zone" }), _jsx("th", { className: "text-left px-3 py-2", children: "User" }), _jsx("th", { className: "text-left px-3 py-2", children: "Title" }), _jsx("th", { className: "text-left px-3 py-2", children: "Detectors" }), _jsx("th", { className: "text-left px-3 py-2", children: "Status" })] }) }), _jsxs("tbody", { className: "divide-y divide-border", children: [alerts.loading && (_jsx("tr", { children: _jsx("td", { colSpan: 7, className: "px-3 py-4 text-gray-500 font-mono", children: "Loading\u2026" }) })), !alerts.loading && visibleAlerts.length === 0 && (_jsx("tr", { children: _jsx("td", { colSpan: 7, className: "px-3 py-4 text-gray-500 font-mono", children: "No alerts to show." }) })), visibleAlerts.map((a) => (_jsxs("tr", { className: "hover:bg-black/30", children: [_jsx("td", { className: "px-3 py-2 text-xs font-mono text-gray-400 whitespace-nowrap", children: formatDateTime(a.created_at) }), _jsx("td", { className: "px-3 py-2", children: _jsx(ClassificationBadge, { classification: a.classification, score: a.score, size: "sm" }) }), _jsx("td", { className: "px-3 py-2 font-mono text-xs", children: a.zone_id }), _jsx("td", { className: "px-3 py-2 font-mono text-xs text-gray-400", children: a.user_id ?? '—' }), _jsx("td", { className: "px-3 py-2", children: a.title }), _jsx("td", { className: "px-3 py-2 text-[10px] font-mono text-gray-500", children: a.contributing_detectors.join(' · ') }), _jsx("td", { className: "px-3 py-2 text-xs font-mono", children: a.acknowledged ? (_jsxs("span", { className: "text-normal", children: ["acked by ", a.acknowledged_by] })) : (_jsx("span", { className: "text-suspect", children: "open" })) })] }, a.alert_id)))] })] })] })] }));
}
