worker_processes auto;
error_log /dev/stderr notice;

events {
    worker_connections 1024;
}

http {
    server {
        listen 9001; # Plaintext WebSocket locally
        
        location / {
            # Remplacer <IP_ORACLE_VM> par la vraie IP publique de la VM Oracle
            proxy_pass https://145.241.162.174:8443;
            
            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            # Enable PQC Key Exchange
            proxy_ssl_protocols TLSv1.3;

            
            # Gateway certificates
            proxy_ssl_certificate /etc/nginx/certs/gateway.crt;
            proxy_ssl_certificate_key /etc/nginx/certs/gateway.key;
            
            # Reverse-proxy identity verification
            proxy_ssl_trusted_certificate /etc/nginx/certs/ca.crt;
            proxy_ssl_verify on;
            proxy_ssl_verify_depth 2;
            proxy_ssl_name middleware;
            proxy_ssl_server_name on;
            
            # Session Resumption
            proxy_ssl_session_reuse on;
        }
    }
}
