"""
Alert schema — published on Kafka topic `alerts.critical`.

An Alert is generated by the AI engine when classification = CRITICAL,
or in some SUSPECT cases (configurable). It is consumed by:
  - the SOC dashboard (red banner, push notification)
  - the notification service (email / SMS / webhook)
  - the audit log (signed and stored 90 days, see retention table 6.1)

An Alert references the EnrichedEvent that triggered it; the dashboard
fetches the full event by ID.
"""

from datetime import datetime, timezone
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator

from .enums import AIClassification


class Alert(BaseModel):
    """A SOC-actionable alert derived from a CRITICAL or SUSPECT event."""

    model_config = ConfigDict(extra="forbid", validate_assignment=True)

    alert_id: UUID = Field(default_factory=uuid4)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    # The event(s) that caused this alert. Always at least one.
    triggering_event_id: UUID
    related_event_ids: list[UUID] = Field(default_factory=list)

    # Repeated from the event for fast filtering on the dashboard
    # without having to join with the events table on every render.
    building_id: str
    zone_id: str
    user_id: Optional[str] = None

    classification: AIClassification
    score: float = Field(..., ge=0.0, le=1.0)

    # Short human-readable summary, e.g. "Forced door in zone Z3, no badge".
    # Generated from the rules engine (deterministic) when possible, falls
    # back to a generic template when only the IF model fired.
    title: str = Field(..., min_length=1, max_length=200)
    description: str = Field(..., min_length=1, max_length=2000)

    # Which detector(s) contributed to this alert -- useful for SOC triage.
    # Examples: ["rule:door_forced", "if:user_zone"]
    contributing_detectors: list[str] = Field(default_factory=list)

    # Suggested automatic action (NOT executed by the AI engine itself,
    # only proposed). The SOC operator decides.
    # Examples: "lock_door:D2-B2", "isolate_vlan:cam-vlan"
    suggested_action: Optional[str] = None

    # Operator workflow fields (filled later by the SOC API).
    acknowledged: bool = False
    acknowledged_by: Optional[str] = None
    acknowledged_at: Optional[datetime] = None

    @field_validator("classification")
    @classmethod
    def _only_actionable(cls, v: AIClassification) -> AIClassification:
        """An alert should never be raised for NORMAL classification."""
        if v == AIClassification.NORMAL:
            raise ValueError(
                "Cannot create an Alert with classification=NORMAL"
            )
        return v

    @field_validator("created_at", "acknowledged_at")
    @classmethod
    def _require_timezone_aware(cls, v: Optional[datetime]) -> Optional[datetime]:
        if v is not None and v.tzinfo is None:
            raise ValueError("datetime fields must be timezone-aware")
        return v
